AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Greengrass Device Lambda

  '
Globals:
  Function:
    Timeout: 100
    MemorySize: 129
    Runtime: nodejs8.10
Resources:
  parkingAlerts:
    Type: AWS::Serverless::Function
    Properties:
      Handler: alerts.handler
      AutoPublishAlias: prod
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaExecute
      - CloudWatchLogsFullAccess
      - AWSIoTEventsFullAccess
      - AWSIoTFullAccess
      - AmazonRDSReadOnlyAccess
      Environment:
        Variables:
          tablename: AWS_PARKING_ALERTS_WARNINGS
      CodeUri: s3://sp-sam-bucket/1f0c6ad7dbfe4c4270f32a86598de541
